canonical:  https://gematik.de/fhir/isik/v2/Basismodul
fhirVersion: 4.0.1
FSHOnly: true
applyExtensionMetadataToRoot: false
id: Implementierungsleitfaden gematik-Basismodul Stufe 1 1.0.0
name: Implementierungsleitfaden gematik-Basismodul Stufe 1 1.0.0
status: active
version: # "1.0.0"
publisher:
  name: Gematik GmbH
  url: https://www.gematik.de/
  email: info@gematik.de
dependencies:
  de.gematik.erezept-workflow.r4: 1.1.1