canonical:  https://gematik.de/fhir/isik/v2/Basismodul
fhirVersion: 4.0.1
FSHOnly: true
applyExtensionMetadataToRoot: false
version: # "1.0.0"
# The following entries are only relevant if FSHOnly: false (i.e. IG publisher is used), otherwise sushi throws a warning
# id:
# name:
# status: active
# publisher:
#   name: Gematik GmbH
#   url: https://www.gematik.de/
#   email: info@gematik.de
dependencies:
  de.basisprofil.r4: 1.4.0
  hl7.fhir.r4.core: 4.0.1
  hl7.fhir.extensions.r5: 4.0.1