name: Render All Diagrams

on:
  push:
    paths:
    - '**/Material/imgsrc/**/*.puml'
    - '**/Material/imgsrc/**/*.drawio'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      # Installs Java distribution for running the plantUML jar
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          check-latest: true
      
      # Install graphviz for plantuml     
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1
      
      # Download plantUML jar 
      - name: Download plantuml file
        run: |
          wget -O plantuml.jar "https://github.com/plantuml/plantuml/releases/latest/download/plantuml.jar" 
                                
       # Clean Folder
      - name: Ensure and clean folder
        run: |
          img_dir=ImplementationGuide/diagrams
          mkdir -p $img_dir
          rm -rf ImplementationGuide/diagrams/*.svg

      # Generate the SVGs from PUML
      - name: Render PUML to SVG and Move files
        run: |
          FileNamePaths=$(find . -path "*/imgsrc/*/*.puml" -exec dirname {} \; | sort -u)
          for dir in $FileNamePaths
          do
            # Render SVGs from PUMLs
            find $dir -name "*.puml" -exec java -jar plantuml.jar -tsvg {} \;
          done

      # Generate the SVGs from DrawIO
      - name: Render DrawIO to SVG with predefined action
        uses: rlespinasse/drawio-export-action@v2
        with:
          path: ./Material/imgsrc/drawio/ 
          output: .
          format: svg
          action-mode: all

      # copies the created png & svg files to the images/diagrams folder and deletes the drawio files
      - name: Move SVGs to target image folder
        run: |
          img_dir=ImplementationGuide/images/diagrams
          inp_dir1=./Material/imgsrc/drawio/
          inp_dir2=./Material/imgsrc/plantuml/
          find $inp_dir1 -name "*.svg" -exec mv {} $img_dir \;
          find $inp_dir2 -name "*.svg" -exec mv {} $img_dir \;
      
      # add and commit the new generated files
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: auto/images-generation
          commit-message: Generated Images from source Code by GitHub Action
          title: Generated Images from GitHub Action
          assignees: ${{ github.actor }}
          reviewers: ${{ github.actor }}
      #- name: Commit and push
      #  run: |
      #    git config --local user.email "action@github.com"
      #    git config --local user.name "GitHub Action"
      #    git add -A
      #    git commit -m "Add rendered PlantUML and DrawIO to SVG diagrams" || exit 0
      #    git push
